-- Example schema generated by Sphere 0.51x MySQL migrations (schema version 4)
-- Replace the `sphere_` prefix below with the value configured via MYSQLPREFIX.
-- Execute as a privileged user inside the target database/schema.
-- The live server will create tables using the configured MySQL charset
-- (default utf8mb4), so adjust the ENGINE clauses below if you use a
-- different connection character set.

START TRANSACTION;

CREATE TABLE IF NOT EXISTS `sphere_schema_version` (
  `id` INT NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `sphere_schema_version` (`id`, `version`) VALUES
  (1, 4),  -- schema revision
  (2, 1),  -- legacy import completed flag
  (3, 0),  -- world save counter placeholder
  (4, 1)   -- last save completed flag
ON DUPLICATE KEY UPDATE `version` = VALUES(`version`);

CREATE TABLE IF NOT EXISTS `sphere_accounts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `plevel` INT NOT NULL DEFAULT 0,
  `priv_flags` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` INT UNSIGNED NOT NULL DEFAULT 0,
  `comment` TEXT NULL,
  `email` VARCHAR(128) NULL,
  `chat_name` VARCHAR(64) NULL,
  `language` CHAR(3) NULL,
  `total_connect_time` INT NOT NULL DEFAULT 0,
  `last_connect_time` INT NOT NULL DEFAULT 0,
  `last_ip` VARCHAR(45) NULL,
  `last_login` DATETIME NULL,
  `first_ip` VARCHAR(45) NULL,
  `first_login` DATETIME NULL,
  `last_char_uid` BIGINT UNSIGNED NULL,
  `email_failures` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_accounts_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_account_emails` (
  `account_id` INT UNSIGNED NOT NULL,
  `sequence` SMALLINT UNSIGNED NOT NULL,
  `message_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`account_id`, `sequence`),
  CONSTRAINT `fk_account_emails_account`
    FOREIGN KEY (`account_id`) REFERENCES `sphere_accounts`(`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_characters` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NULL,
  `name` VARCHAR(64) NULL,
  `body_id` INT NULL,
  `position_x` INT NULL,
  `position_y` INT NULL,
  `position_z` INT NULL,
  `map_plane` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `ix_characters_account` (`account_id`),
  CONSTRAINT `fk_characters_account`
    FOREIGN KEY (`account_id`) REFERENCES `sphere_accounts`(`id`)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_items` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `container_uid` BIGINT UNSIGNED NULL,
  `owner_uid` BIGINT UNSIGNED NULL,
  `type` INT UNSIGNED NOT NULL DEFAULT 0,
  `amount` INT UNSIGNED NOT NULL DEFAULT 0,
  `color` INT UNSIGNED NOT NULL DEFAULT 0,
  `position_x` INT NULL,
  `position_y` INT NULL,
  `position_z` INT NULL,
  `map_plane` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `ix_items_container` (`container_uid`),
  KEY `ix_items_owner` (`owner_uid`),
  CONSTRAINT `fk_items_container`
    FOREIGN KEY (`container_uid`) REFERENCES `sphere_items`(`uid`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_items_owner`
    FOREIGN KEY (`owner_uid`) REFERENCES `sphere_characters`(`uid`)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_item_props` (
  `item_uid` BIGINT UNSIGNED NOT NULL,
  `prop` VARCHAR(64) NOT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`item_uid`, `prop`),
  CONSTRAINT `fk_itemprops_item`
    FOREIGN KEY (`item_uid`) REFERENCES `sphere_items`(`uid`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_sectors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `map_plane` INT NOT NULL,
  `x1` INT NOT NULL,
  `y1` INT NOT NULL,
  `x2` INT NOT NULL,
  `y2` INT NOT NULL,
  `last_update` DATETIME NULL,
  `has_light_override` TINYINT(1) NOT NULL DEFAULT 0,
  `local_light` INT NULL,
  `has_rain_override` TINYINT(1) NOT NULL DEFAULT 0,
  `rain_chance` INT NULL,
  `has_cold_override` TINYINT(1) NOT NULL DEFAULT 0,
  `cold_chance` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_sectors_bounds` (`map_plane`, `x1`, `y1`, `x2`, `y2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_gm_pages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NULL,
  `account_name` VARCHAR(32) NULL,
  `character_uid` BIGINT UNSIGNED NULL,
  `reason` TEXT NULL,
  `status` INT UNSIGNED NOT NULL DEFAULT 0,
  `page_time` BIGINT NULL,
  `pos_x` INT NULL,
  `pos_y` INT NULL,
  `pos_z` INT NULL,
  `map_plane` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_gm_pages_account` (`account_id`),
  KEY `ix_gm_pages_character` (`character_uid`),
  CONSTRAINT `fk_gm_pages_account`
    FOREIGN KEY (`account_id`) REFERENCES `sphere_accounts`(`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_gm_pages_character`
    FOREIGN KEY (`character_uid`) REFERENCES `sphere_characters`(`uid`)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_servers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `address` VARCHAR(128) NULL,
  `port` INT NULL,
  `status` INT UNSIGNED NOT NULL DEFAULT 0,
  `time_zone` INT NOT NULL DEFAULT 0,
  `clients_avg` INT NOT NULL DEFAULT 0,
  `url` VARCHAR(255) NULL,
  `email` VARCHAR(128) NULL,
  `register_password` VARCHAR(64) NULL,
  `notes` TEXT NULL,
  `language` VARCHAR(16) NULL,
  `version` VARCHAR(64) NULL,
  `acc_app` INT NOT NULL DEFAULT 0,
  `last_valid_seconds` INT NULL,
  `age_hours` INT NULL,
  `last_seen` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_servers_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_timers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `character_uid` BIGINT UNSIGNED NULL,
  `item_uid` BIGINT UNSIGNED NULL,
  `expires_at` BIGINT NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `data` TEXT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_timers_character` (`character_uid`),
  KEY `ix_timers_item` (`item_uid`),
  CONSTRAINT `fk_timers_character`
    FOREIGN KEY (`character_uid`) REFERENCES `sphere_characters`(`uid`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_timers_item`
    FOREIGN KEY (`item_uid`) REFERENCES `sphere_items`(`uid`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_world_objects` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `object_type` VARCHAR(32) NOT NULL,
  `object_subtype` VARCHAR(64) NULL,
  `name` VARCHAR(128) NULL,
  `account_id` INT UNSIGNED NULL,
  `container_uid` BIGINT UNSIGNED NULL,
  `top_level_uid` BIGINT UNSIGNED NULL,
  `position_x` INT NULL,
  `position_y` INT NULL,
  `position_z` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  KEY `ix_world_objects_type` (`object_type`),
  KEY `ix_world_objects_account` (`account_id`),
  KEY `ix_world_objects_container` (`container_uid`),
  KEY `ix_world_objects_top` (`top_level_uid`),
  CONSTRAINT `fk_world_objects_account`
    FOREIGN KEY (`account_id`) REFERENCES `sphere_accounts`(`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_world_objects_container`
    FOREIGN KEY (`container_uid`) REFERENCES `sphere_world_objects`(`uid`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_world_objects_top`
    FOREIGN KEY (`top_level_uid`) REFERENCES `sphere_world_objects`(`uid`)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_world_object_data` (
  `object_uid` BIGINT UNSIGNED NOT NULL,
  `data` LONGTEXT NOT NULL,
  `checksum` VARCHAR(64) NULL,
  PRIMARY KEY (`object_uid`),
  CONSTRAINT `fk_world_object_data_object`
    FOREIGN KEY (`object_uid`) REFERENCES `sphere_world_objects`(`uid`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_world_object_components` (
  `object_uid` BIGINT UNSIGNED NOT NULL,
  `component` VARCHAR(32) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `sequence` INT NOT NULL DEFAULT 0,
  `value` LONGTEXT NULL,
  PRIMARY KEY (`object_uid`,`component`,`name`,`sequence`),
  KEY `ix_world_components_component` (`component`),
  CONSTRAINT `fk_world_components_object`
    FOREIGN KEY (`object_uid`) REFERENCES `sphere_world_objects`(`uid`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_world_object_relations` (
  `parent_uid` BIGINT UNSIGNED NOT NULL,
  `child_uid` BIGINT UNSIGNED NOT NULL,
  `relation` VARCHAR(32) NOT NULL,
  `sequence` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`parent_uid`,`child_uid`,`relation`,`sequence`),
  KEY `ix_world_relations_child` (`child_uid`),
  CONSTRAINT `fk_world_relations_parent`
    FOREIGN KEY (`parent_uid`) REFERENCES `sphere_world_objects`(`uid`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_world_relations_child`
    FOREIGN KEY (`child_uid`) REFERENCES `sphere_world_objects`(`uid`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_world_savepoints` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `objects_count` INT NOT NULL DEFAULT 0,
  `checksum` VARCHAR(64) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sphere_world_object_audit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `object_uid` BIGINT UNSIGNED NOT NULL,
  `changed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `change_type` VARCHAR(32) NOT NULL,
  `data_before` LONGTEXT NULL,
  `data_after` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_world_audit_object` (`object_uid`),
  CONSTRAINT `fk_world_audit_object`
    FOREIGN KEY (`object_uid`) REFERENCES `sphere_world_objects`(`uid`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;
